### ISSUE TITLE
Move the information from the WikiTree+ manifest.json file into the main manifest.json file.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#10]
The stuff in the WikiTree+ manifest file https://github.com/wikitree/wikitree-browser-extension/blob/development/features/wt%2B/manifest.json needs to be integrated into the main manifest file https://github.com/wikitree/wikitree-browser-extension/blob/development/manifest.json.

**Comment by Lesko987** [comment]
It already is. I just didn't delete the one on WT+ folder. It is now deleted.
