### ISSUE TITLE
Switch all existing features to use checkIfFeatureEnabled

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#103]
When I implemented the options system I only switched the agc feature to use `checkIfFeatureEnabled` rather than `chrome.storage.sync.get` directly. This was so tha people could see how to use it.

Since then several other features have switched over to use it.

So I can now go through all the remaining features and switch them over.

**Comment by ke4tch** [comment]
Please leave BioCheck. I have done this and would like to avoid commit conflicts
