### ISSUE TITLE
Redirect external links

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#104]
NOTE: this is something that I plan to work on myself if I have time.

**Is your feature request related to a problem? Please describe.**
When a profile contains a link to an Ancestry or FindMyPast record or image then it points to a specific domain. E.g. ancestry.com or ancestry.co.uk. If the user's subscription is on a different domain then clicking on the link asks them to sign up for an Ancestry account.

**Describe the solution you'd like**
When the profile page loads it would (if this feature is enabled) find all such links and redirect them to the user's preferred domain.

The preferred domain for each site would be set in the options for this feature.

**Describe alternatives you've considered**
I have partially addressed this in the WikiTree Sourcer extension using a context menu. The user can right-click on the link and select the option "Sourcer: Open link in new tab" and it will use the domain set in the Sourcer options.

**Comment by Lesko987** [comment]
This could be extended to correct old ancestry links, that no longer work.

I do this in WT+ if you click Automated cleanup on edit page. But it could correct the links also on normal pages. 

I have the definition in [templatesInclude.json](https://github.com/wikitree/wikitree-browser-extension/blob/development/src/features/wt%2B/templatesInclude.json) But this part defines the replaces.

	"description": "Ancestry URL",
	"actions": [{
	},{
		"description": "old record URL to new",
		"action": "replaceRegEx",
		"from": "http://trees\\.ancestry\\.com/rd\\?f=sse&",
		"to": "http://search.ancestry.com/cgi-bin/sse.dll?",
		"flags": "mg"
	},{
		"description": "old tree URL to new",
		"action": "replaceRegEx",
		"from": "https?://(www\\.ancestry\\.com/pt/PersonMatch|trees\\.ancestry\\.com/pt/AMTCitationRedir)\\.aspx\\?tid=(\\d{2,})&pid=([-]?\\d{6,})",
		"to": "https://www.ancestry.com/family-tree/person/tree/$2/person/$3/facts",
		"flags": "mg"
	},{
		"description": "old tree URL to new (no person)",
		"action": "replaceRegEx",
		"from": "https?://(www\\.ancestry\\.com/pt/PersonMatch|trees\\.ancestry\\.com/pt/AMTCitationRedir)\\.aspx\\?tid=(\\d{2,})&pid=(\\d{0,5})",
		"to": "https://www.ancestry.com/family-tree/tree/$2/family",
		"flags": "mg"
	}]

**Comment by RobPavey** [comment]
> This could be extended to correct old ancestry links, that no longer work.

Is there a quick way in WT+ to find some profiles with these old links?

**Comment by RobPavey** [comment]
@Lesko987 Also, do you think that for those old ancestry links it would be good to make them display in a different color to alert the user that they should be fixed?

**Comment by Lesko987** [comment]
No. I don't have urls indexed. Here are some examples.
1) 
https://www.wikitree.com/wiki/Freestone-4
https://www.wikitree.com/wiki/Winslow-2
2)
https://www.wikitree.com/wiki/Welert-1
https://www.wikitree.com/wiki/Cox-146
3)
https://www.wikitree.com/wiki/Haraldsdatter-11
