### ISSUE TITLE
Decide a coding style guide for the project

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#11]
It is important to at least agree on an indentation style and a brace layout style.

**Comment by RobPavey** [comment]
I would recommend choosing an existing style rather than inventing a new one.

I would recommend Google's style: https://google.github.io/styleguide/jsguide.html

**Comment by ke4tch** [comment]
Most of the Google style items look good to me. Just reviewing that has pointed out some things for me to clean up as a JavaScript newbie.

**Comment by ke4tch** [comment]
Here are some other coding style guidelines to consider:

https://www.w3schools.com/js/js_conventions.asp

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript

The former is short and sweet, the latter similar to the Google guidelines without Google specific features.

**Comment by shogenapps** [comment]
Although I hadn't seen the Google standards until Rob posted a link to them recently, they seem like a very good standard to follow, and I will try to follow that.  And I've just discovered Prettier, thanks to the comments above, so that will help.

**Comment by RobPavey** [comment]
We have just tried out prettier on the Sourcer project and the defaults look OK to me other than the default line wrap which is 80 I believe. I suggest changing that to 120.

**Comment by bcaseyrls** [comment]
I suggest we use the same .prettierrc configuration file for both wikitree-dynamic-tree and wikitree-browser-extension. The dynamic tree repo has a (draft) .prettierrc file (https://github.com/wikitree/wikitree-dynamic-tree/blob/main/.prettierrc) which sets the line length to 120. See https://github.com/wikitree/wikitree-dynamic-tree/issues/31 and https://github.com/wikitree/wikitree-dynamic-tree/pull/34.

**Comment by RobPavey** [comment]
I'm not sure how that prettierrc differs from the defaults. I would just go with the defaults apart from the line length.

**Comment by ke4tch** [comment]
Does it make sense to have a prettier webpack target so that you can npm run prettier as you would for npm run lint

**Comment by RobPavey** [comment]
Or it could be setup to run on commit also.

**Comment by MichalVasut** [comment]
Prettier has  the option to run [from command line](https://prettier.io/docs/en/cli.html) and overall it integrates very well. ;-)

**Comment by jmegenealogy** [comment]
> Or it could be setup to run on commit also.

Just putting this here for later: https://mskelton.dev/blog/auto-formatting-code-using-prettier-and-github-actions

**Comment by PeWu** [comment]
Prettier can also be run with GitHub Actions in the form of a test ([prettier --check](https://prettier.io/docs/en/cli.html#--check)). If the code is not the same as run through prettier, the PR will have a check failure.

In terms of style, my preference is to stick with whatever is the default. If prettier is used, use its defaults. Arguing about style is quite counterproductive. Everyone has different preferences. Sticking to defaults is always the least controversial even though there is someone that made that decision.

**Comment by shogenapps** [comment]
Let's use the .prettierrc file that is being used on the dynamic tree side of things, as Brian suggested 13 days ago.  Everyone may have their preferences, but someone (maybe Brian?) has made a decision about standard formatting.  Why don't we just go with that?

**Comment by RobPavey** [comment]
> Let's use the .prettierrc file that is being used on the dynamic tree side of things, as Brian suggested 13 days ago. Everyone may have their preferences, but someone (maybe Brian?) has made a decision about standard formatting. Why don't we just go with that?

It would be nice if there was some rationale for the rules we choose. Like a vote among the the current contributors. Or looking at what the general standard is. As Kay pointed out in Discord, most of the coding guidelines for js use an indentation of 2.

**Comment by shogenapps** [comment]
On second thoughts, maybe some people here don't want to use the same file as the dynamic tree people.  I'll do anything.  If most people here want Prettier defaults and printWidth of 120, I'll do that.  I'm going to do that now until someone tells me otherwise.

**Comment by shogenapps** [comment]
> > Let's use the .prettierrc file that is being used on the dynamic tree side of things, as Brian suggested 13 days ago. Everyone may have their preferences, but someone (maybe Brian?) has made a decision about standard formatting. Why don't we just go with that?
> 
> It would be nice if there was some rationale for the rules we choose. Like a vote among the the current contributors. Or looking at what the general standard is. As Kay pointed out in Discord, most of the coding guidelines for js use an indentation of 2.
I read the Google style rules you posted recently and they had a 2 space indentation.  If it's good enough for Google...

**Comment by RobPavey** [comment]
> As for me, I don't really care if it'll be 80 or 120 charcters (120 works for us at work, but it was about the agreement in team).

I'm sure I can get used to whatever is agreed but the 80 character printWidth is rather jarring to me at the moment. The last place I worked had guidelines against using abbreviations and encouraged more verbose function and variable names. So a function call with a few parameters that is indented a few levels gets switched from one line to five lines by prettier when using printWidth of 80.

Example this:
```
function fillDefaultValuesForOptions(defaultValues, options, useTestDefaults, sync) {
  for (let option of options) {
    if (option.type == OptionType.GROUP) {
      if (option.options) {
        fillDefaultValuesForOptions(defaultValues, option.options, useTestDefaults);
      }
    }
  } 
}
```
becomes this:
```
function fillDefaultValuesForOptions(
  defaultValues,
  options,
  useTestDefaults,
  sync
) {
  for (let option of options) {
    if (option.type == OptionType.GROUP) {
      if (option.options) {
        fillDefaultValuesForOptions(
          defaultValues,
          option.options,
          useTestDefaults
        );
      }
    }
  } 
}
```
Just providing that hypothetical example so people can judge which they find more readable.

I wonder if a printWidth of 80 would encourage me to abbreviate names more.

Like I say, I'm sure I can get used to it if that is what people prefer.

**Comment by MichalVasut** [comment]
@RobPavey 

> I will put up a PR with a .prettierrc and we can decide the issue there

we already have one here: https://github.com/wikitree/wikitree-dynamic-tree/blob/main/.prettierrc

feel free to use it

**Comment by ke4tch** [comment]
So could the .prettierrc become a test case for files that need to be in both the dynamic tree and the browser?

**Comment by RobPavey** [comment]
> So could the .prettierrc become a test case for files that need to be in both the dynamic tree and the browser?

Could you elaborate Kay? I'm not sure what you mean.

**Comment by RobPavey** [comment]
> We have one single .prettierrc file that we want to include in the build for both the dynamic tree and the browser. So how can we manage this from a single baseline.

I guess the question is: does it matter if we have different .prettierrc rules in wikitree-browser-extension and wikitree-dynamic-tree? If we are doing auto-format on commit (or save or something like that) then if you copy a file from one project to the other it will just be auto-formatted to match the style of the project.

**Comment by harrislineage** [comment]
> I'm sure I can get used to whatever is agreed but the 80 character printWidth is rather jarring to me at the moment.

100% agree with @RobPavey here. I would vote for 120 printWidth, but can adapt to 80 if that is the consensus.

**Comment by shogenapps** [comment]
Done.
