### ISSUE TITLE
Common Syntax checking for extension

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#118]
We did agree to use Prettier for code formatting. How about syntax checking. 

Today I tried esLint and after making it work, I corrected a few errors, that would cause errors in Chrome. 

I intend to use it, but it would be usefull for others. I am sure some of you are already using it.

Or are you using something else?

Should we have a common configuration for it?

**Comment by jmegenealogy** [comment]
I think I'm already using eslint in VS Code so I have no problem with encouraging its use.

**Comment by RobPavey** [comment]
I'm happy to use it. Is it possible to get down to now errors or warnings? I haven't used it yet.

**Comment by shogenapps** [comment]
I already have ESLint installed, too.

**Comment by RobPavey** [comment]
I have played with it a bit. I'm not sure about how to deal with this one:

```
  function onChange(event) {
    saveFeatureOptions(featureData);
  }
```
`148:21  error  'event' is defined but never used  no-unused-vars`

I can just delete "event" but it is kind of nice to know what params a standard callback like this has. What do others think?

**Comment by RobPavey** [comment]
This is the config I am using so far (`.eslintrc.js`):

```
module.exports = {
  env: {
    browser: true,
    es2021: true,
    webextensions: true,
  },
  extends: "eslint:recommended",
  overrides: [],
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  rules: {},
};
```

**Comment by RobPavey** [comment]
> I think I'm already using eslint in VS Code so I have no problem with encouraging its use.

Have you installed a plugin? I have a "PROBLEMS" tab in the window where the terminal is in vscode. But it doesn't find all the issues that eslint does.

**Comment by jmegenealogy** [comment]
I have this one installed: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by ke4tch** [comment]
I ran into a nightmare trying to upgrade to a later eslint (that would allow multiple #privateMethod) that ended up being incompatible with npm. Part of this nightmare is also using vue-cli and its dependencies. It's going to take me some significant work to resolve this. In the meantime I am using the older esline.

**Comment by shogenapps** [comment]
Done.
