### ISSUE TITLE
How to keep the code that ships with extension separate from docs and test framework

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#12]
There are different ways to do it but I would suggest reorganizing the folder structure so that the Chrome extension itself is in a subfolder. That way it is easy to make a zip file to submit to be published. There is no reason to be publishing your readme file and test framework etc.

**Comment by Lesko987** [comment]
We could name subfolders that are not needed in the release with underline at the beggining like _Whatever. on publish those folders could be excluded.

**Comment by ke4tch** [comment]
Isn't there an issue discussion use of webpack? Or maybe Vite. 

And this applies to both family view and extension?
