### ISSUE TITLE
Reading mode

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#125]
**Is your feature request related to a problem? Please describe.**
Not a problem exactly but WikiTree pages can seem rather cluttered when you just want to browse through the tree and read profiles. For example I would like to be able to hide the whole right hand column that shows all the linked images among other things.

**Describe the solution you'd like**
Something called "Reading mode" or "Minimal mode". It would have several options where the user can select what they want hidden in reading mode.

This is probably something that the user wants to easily toggle on and off without going to the options. So, when the feature is enabled, there would be a toggle button near the top of the profile that toggles reading mode on and off.

**Describe alternatives you've considered**
This is different to the "printer Friendly Bio" since that produces a PDF. In reading mode:
- You can still use links to go to parents, children etc and thus browse the tree.
- You can still interact in other ways

Reading mode would stay on when you moved from profile to profile until you toggled it off.

**Additional context**

Things that could be optionally hidden in reading mode (these would be individual checkboxes on the options for reading mode):

1. The right hand column. This would hide the "six columns" div and expand the left column t be the full 16 columns.
2. All tables in the bio
3. The Sources section and all inline ref links (e.g. [1])
4. The 3 lines that name the profile manager and last edited etc.
5. Possibly the tabs (Edit, Images etc)
6. All inline images in the bio along with their captions
7. The memories, comments and matches/merges sections
8. The line of buttons under the tabs ([Comments ][Family Group][Matches ][Sources])

**Possible interactions**

This feature might be incompatible with other features that modify the profile layout.

**Comment by shogenapps** [comment]
I like this idea.  I want to add vertical family lists with gendered colours and dates at some point (see the vertical lists in WT BEE).  I'm not sure if this will conflict with it, will it?

**Comment by RobPavey** [comment]
I'm not planning to work on this any time soon so if someone else would like to that is fine with me. 

Regarding conflicts, in theory any two features that modify the document could conflict. I'm not sure what the best way to handle conflicts is.

**Comment by jonathanduke** [comment]
This has been implemented and merged into the development branch. I also added additional options for hiding elements:
![reading-mode](https://user-images.githubusercontent.com/18707259/224494124-1e1386d9-6ac8-4c7d-9451-1b595de08d06.png)

I started with the accessibility options to help make sources more readable and transitioned into this. I thought about merging it all into reading mode, but I thought it might be better to make the toggle on/off only apply to the hiding of elements while the accessibility options apply to the formatting of elements that should apply whether or not reading mode is on.

Try them out with [Charles Schulz](https://www.wikitree.com/wiki/Schulz-482) and [Elvis Presley](https://www.wikitree.com/wiki/Presley-155). It even works with [space pages](https://www.wikitree.com/wiki/Space:WikiTree_Browser_Extension) and [categories](https://www.wikitree.com/wiki/Category:Odd_Fellows_Cemetery,_Carthage,_Texas).

**Comment by jonathanduke** [comment]
This was included in the stable 1.4 [release](https://www.wikitree.com/g2g/1563396/wikitree-browser-extension-new-features). More details on the options [here](https://www.wikitree.com/wiki/Space:WikiTree_Readability_Options).

Additional customizations since the initial preview (like being able to hide individual sections of the sidebar) have made this compatible with some of Ian's other features like the vertical family lists (mentioned above) and My Menu. Other features like collapsible sources and formatting source numbers were merged into this one.
