### ISSUE TITLE
Bug in source preview feature

### ISSUE THREAD

**Issue by shogenapps** [wikitree/wikitree-browser-extension#133]
I've found an unusual condition that makes the source preview feature throw errors.   If a profile doesn't have a <references /> tag, but it does have inline references, and you do a preview, and then hover over a reference number, the source preview feature throws this error:

`sourcepreview.js:17 Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')
    at HTMLElement.<anonymous> (sourcepreview.js:17:1)
    at HTMLElement.handle (jquery.js:5895:1)
    at HTMLElement.dispatch (jquery.js:5430:1)
    at elemData.handle (jquery.js:5234:1)
(anonymous) @ sourcepreview.js:17
handle @ jquery.js:5895
dispatch @ jquery.js:5430
elemData.handle @ jquery.js:5234`

**Comment by harrislineage** [comment]
@shogenapps can you provide an example profile? I have ran a few tests and I am unable to reproduce this exact error.

Tested Profiles:
- https://www.wikitree.com/wiki/Hendrix-418
- https://www.wikitree.com/wiki/Overeem-10
- https://www.wikitree.com/wiki/Taillon-192

I am going to start on a possible workaround, but more profiles to test with would be appreciated.
