### ISSUE TITLE
#addCategoryInput Display

### ISSUE THREAD

**Issue by harrislineage** [wikitree/wikitree-browser-extension#137]
**Describe the bug**
#addCategoryInput is displaying beside #editToolbarExt instead of underneath on Category Pages.

**To Reproduce**
1. Go to [Category:Texas](https://www.wikitree.com/wiki/Category:Texas)
2. Click on [edit]
3. Select the addCategory button

![image](https://user-images.githubusercontent.com/80127898/199584866-8e457011-c2bd-4d2d-bdaf-ff577681c962.png)

**Expected behavior**
#addCategoryInput should display underneath #editToolbarExt on Category: pages as it does on Space: and other profile pages.

![image](https://user-images.githubusercontent.com/80127898/199585345-d47be60f-d15a-4273-8f7a-bacbb355e4b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 106.0.5249.119
 - Extension Version: 1.0.1

**Comment by Lesko987** [comment]
Resolved,
