### ISSUE TITLE
myCustomMenuContainer Display

### ISSUE THREAD

**Issue by harrislineage** [wikitree/wikitree-browser-extension#138]
**Describe the bug**
#myCustomMenuContainer is forced below the WikiTree Logo / G2G images.

**To Reproduce**
1. Go to [G2G](https://www.wikitree.com/g2g/)
2. See error

![image](https://user-images.githubusercontent.com/80127898/199593081-02c58e3a-65b0-4326-9523-fd2a1130508b.png)

**Expected behavior**
#myCustomMenuContainer should be inline with the other menu items.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- OS: Windows 10 Pro
- Browser: Chrome
- Version: 106.0.5249.119
- Extension Version: 1.0.1

**Comment by shogenapps** [comment]
Not an error/bug.
