### ISSUE TITLE
.theClipboardButtons Display

### ISSUE THREAD

**Issue by harrislineage** [wikitree/wikitree-browser-extension#139]
**Describe the bug**
.theClipboardButtons appear in random positions on the page depending on the page type or mode (edit) being viewed. Positioning is also inconsistent on the same page types and mode; Profile-1 Edit Mode is different than Profile-2 Edit Mode - see screenshots #4 and #5.

**Expected behavior**
.theClipboardButtons should appear in a consistent location.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/80127898/199594005-d47735b5-2cce-4029-a224-c41cf6d38195.png)
2. ![image](https://user-images.githubusercontent.com/80127898/199594112-c27517c8-922a-422e-a25e-c3711ca6dfb3.png)
3. ![image](https://user-images.githubusercontent.com/80127898/199594138-ec8d71fb-f4f7-4235-ab10-dead8466336a.png)
4. ![image](https://user-images.githubusercontent.com/80127898/199594166-fe9eccdd-5ce0-4566-9d15-3bfb1a55d10b.png)
5. ![image](https://user-images.githubusercontent.com/80127898/199594296-835c2e19-3529-48b4-adcc-5efac47cb111.png)
6. ![image](https://user-images.githubusercontent.com/80127898/199596190-5ba30bd4-bdae-4dbf-a076-07ba1d9267d0.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro
- Browser: Chrome
- Version: 106.0.5249.119
- Extension Version: 1.0.1

**Comment by shogenapps** [comment]
The positions are not random.  I selected them as the best places for each page.  The inconsistent positioning in the toolbar is a matter of timing - whichever loads first is first. I'm not really sure what to do about that one.  Suggestions are welcome.

**Comment by RobPavey** [comment]
A possible fix for the the timing issue is similar to what I did for AGC:
    toolbar.insertBefore(agcButton, toolbar.firstChild);
That will always put them on the left.
Not sure how to always put them on the right unless you do a timeout until the standard buttons have been added.

**Comment by shogenapps** [comment]
Yes.  Thanks.  I don't really want it on the left, so I'll add a timeout.

**Comment by MichalVasut** [comment]
> I don't really want it on the left, so I'll add a timeout.

Is the timeout really necessary? Standard javascript has [`DOMContentLoaded event`](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) that will wait till the document DOM is loaded (there are all elements). According to Stackoverflow you cannot use this, because that event is already fired in the time the extension is injected into the page, but there is another solution:

https://stackoverflow.com/a/43245774
