### ISSUE TITLE
What's new protocol

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#146]
Now after initial release, we should have a what's new more exposed. I am having trouble finding it.

We need to write instructions on where to describe new things.

As I am searching arround I found:

* New fetures with an option item should be added here https://www.wikitree.com/wiki/Space:WikiTree_Browser_Extension with * and a description
* Each change worth mentioning should be added here https://www.wikitree.com/wiki/Space:WikiTree_Browser_Extension_Update I would recommend adding following style: 

```
=== v.1.0.1.3 (Development)  ===
* WikiTree+ Edit Helper
** Added Cemetery Category Picker that also searches in aka and locations defined in CategoryInfoBox on Cemetery category.
:: Additional description in new paragraph

=== v.1.0.1.2 (Preview) 2022-11-03 (UTC) ===
* '''Category Display'''
Changes the location of Categories to the top of the Bio.

=== v.1.0.1.1  (Preview) 2022-11-03 (UTC) ===
* '''G2G Options'''
**  Checkmarks to show questions you have visited

== v.1.0.1.0 initial Release 2022-11-03 (UTC) ==
```
Let's say the option name is bolded if it is a new option
If you need to write 2 paragraphs use :: at the beggining of the line.

When new ZIP files are prepared, the Development changes to Preview and new Development is added at the top with version increased by 1.

What are your thoughts?

**Comment by shogenapps** [comment]
Personally, I don't think the 'development' part of it is necessary, but I could be wrong.  I think the update page should be updated whenever a new version is uploaded (apart from just big fixes).  And the main page can be updated at the same time.  Also, the background.js file should be edited to open the page on update. After creating the zip file(s), comment out the bit that opens the update page.   (About having trouble finding the update page, I guess we could add a link to it on the main page.)

The :: sounds like a good idea.

At the start of the month, we need the stable version to have an update page open up. I'll create that page (though the current one is called '...Update', so I'm not sure what to do about the name of it).  (Of course, anyone else can make that page, too.)

I'm hoping that we can have better explanations than we currently have, as I've seen that some people are already confused by some things.

**Comment by shogenapps** [comment]
Done.
