### ISSUE TITLE
Directions for users to configure extension

### ISSUE THREAD

**Issue by ke4tch** [wikitree/wikitree-browser-extension#152]
The G2G thread about the new extension has questions from users (of both Chrome and Firefox) about how to configure the extension.

We should have some concise, simple directions for configuration. 

Where should this go? If they haven't figured out how to install the extension, it can't go in the extension. A G2G post would get stale very quickly. So the extension is separate from the core, but should there be some basic help about how to find, install, and open configuration page for the extension on the Help pages?

**Comment by shogenapps** [comment]
I've updated the space page with more information.  Feel free to add to it or edit it.  Yes, I think there should be something about the extension on Help pages and (definitely) on the Apps page.

**Comment by jmegenealogy** [comment]
I'll create a basic Help page (so people can find it when searching the Help pages), and link to the Space page from there.

Most details should be on the Space page (since only Leaders/Sysops can edit the Help pages) -- so any suggestions on what I should put on the Help page?

**Comment by ke4tch** [comment]
I would recommend something like, well, its a really rough draft

If you are using a Chrome browser or any of the following browsers Opera, Edge, Brave, and Vivaldi:
1. Install the extension blah blah
2. To configure the installed extension:
- click the tool icon in the upper right corner of the browser window
- under Extensions click on the three ... by WikiTree Browser Extension and then click Manage Extension
- on the page for the extension scroll down and click on Extension Options. 
- on the WikiTree Extension options page click the button(s) to turn feature(s) on or off

If you are using the Firefox browser:
1. From the Tools menu in the Firefox top toolbar, select Add-ons and Themes
2. Search for WikiTree Browser to find the extension, then click on the WikiTree Browser Extension to install it
3. The Tools->Add-ons and Themes menu opens your Manage Your Extensions page. From this page, click on the ... next to WikiTree Browser Extension
4. Click Manage to see what version you have and to see the release notes
5. Click Preferences to open the Extension Options page 
6. - on the WikiTree Extension options page click the button(s) to turn feature(s) on or off

**Comment by RobPavey** [comment]
The way I configure the Chrome extension is a different way which seems easier to me:

After installing:
- Click the puzzle piece icon to the right of the URL bar and press the pin next to WBE

Each time you want to edit configuration:
- Click the WBE icon (tree) to the left of the puzzle piece and select "Options..."

**Comment by Lesko987** [comment]
I think extension deserves a link from the main WikiTree Menus. Maybe under Help / Extension.

It could link to Chrome store, but that is a problem for Firefox and IOS. Next best thing would be a Help:Extension page with links to all three stores and some First steps for each browser. Steve, Jamie and me can update the page as necessary. And there would also be links to Space pages with detailed descriptions.

**Comment by shogenapps** [comment]
Why not just link the help page to the space page and improve that?

**Comment by shogenapps** [comment]
Sorted.
