### ISSUE TITLE
Sort Badges / Feed Detection

### ISSUE THREAD

**Issue by harrislineage** [wikitree/wikitree-browser-extension#183]
#86 introduced hiding/sorting buttons on Special:Badges with:

```
if ($("body.page-Special_Badges").length) {
    ...
}
```

Suggest moving to URL or Text detection to prevent badges showing on badge feed pages, such as https://www.wikitree.com/index.php?title=Special:Badges&b=coordinator.

**Comment by shogenapps** [comment]
I think I've already fixed this. (#177)  Are you using the latest version?

**Comment by harrislineage** [comment]
I am on the latest version (or at least thought I was). I will recompile and see how it goes. Sorry for the intrusion on my part 😫
