### ISSUE TITLE
Custom Change Summary

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#188]
**Describe the bug**
Custom Change Summarychanges appearance of the save button on Category pages. Probably also on other types of pages.

**To Reproduce**
1. Edit a category
2. https://www.wikitree.com/index.php?title=Category:Stoney_Point_Cemetery%2C_Scranton%2C_Arkansas&action=edit

**Expected behavior**
Save button should not change.

This is a CSS style changing the appearance
#wpSave,
#wpSaveDraft {
  font-size: 1em;
  padding: 0.5em;
}
I guess the CSS shouldn't be loaded if it does nothing on the page.

**Comment by shogenapps** [comment]
I've removed those lines.
