### ISSUE TITLE
Older versions of Safari don't support "lookbehind" in regular expressions

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#267]
The extension will run on the latest version of Safari, but versions released before January 2023 (https://bugs.webkit.org/show_bug.cgi?id=174931) throw the error "Invalid regular expression: invalid group specifier name".

See https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group for more info.

**Comment by shogenapps** [comment]
Noted.
