### ISSUE TITLE
Add ability to copy the bio text from the changes page

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#413]
**Is your feature request related to a problem? Please describe.**
When looking at a change on the changes tab of a profile I often want to copy the bio text from the before or after side. This isn't possible by normal selection and copy since that ends up copying both sides with + and - characters.

**Describe the solution you'd like**
Have a WBE option to add a button above the bio text box on each side saying "Copy Biography"

**Describe alternatives you've considered**
There could be some way to select just parts of the bio text to copy but I don't see an easy way to do that.

**Comment by RobPavey** [comment]
To give a bit more reason on why this would be useful...

For developers and debugging - if AGC for example goes wrong it is useful to be able to look at the changes and copy the bio from before running AGC. It can then be put in the unit tests. Same might be true for Auto Bio.

For regular WikiTreer's. If something has gotten messed up in the profile but they don't want to restore and lose data fields changes they can copy the old version of the bio and then paste that into the profile in edit mode and edit to get the parts they want from the old and new versions.

**Comment by shogenapps** [comment]
Done.
