### ISSUE TITLE
Auto Bio doesn't respect 'Household table in biography' setting when off, incorrectly nests family census tables

### ISSUE THREAD

**Issue by dngrlux** [wikitree/wikitree-browser-extension#420]
**Describe the bug**
The Auto Bio feature has not been working properly in the most recent versions of WBE. With the 'Household table in the biography' option turned off, it still places tables in the biography. It has also been incorrectly nesting tables on most of the profiles I try with Auto Bio. It renders the feature unusable.

**To Reproduce**
1. Go to a profile, for example https://www.wikitree.com/wiki/Marsh-10401
2. Click on Edit, then Auto Bio.
3. Click on Preview.
4. See improper tables and unusable profile edit.
4b. Also spot the regressions in language "married was a mother-in-law, in the household of…" compared to the prior "was the married mother-in-law of …".

**Expected behavior**
Prior versions of WBE/Auto Bio did not experience this.

**Screenshots**
![Screen Shot 2023-08-06 at 4 42 38 PM](https://github.com/wikitree/wikitree-browser-extension/assets/12442027/e965b043-1857-4e5b-abb8-69b9999c87cd)

**Desktop:**
 - OS: macOS 12.6.5
 - Browser: Chrome 115.0.5790.170 (Official Build) (arm64)
 - Extension Version: 1.8.5

**Additional context**
I have tested with similar results when resetting WBE settings. I have also toggled the Household table option back on and off. I have restarted Chrome. I have turned off all other relevant extensions and tested again.

**Comment by shogenapps** [comment]
Thanks.
