### ISSUE TITLE
Names and DOBs of living non-members are added to the bio when Auto Bio is used

### ISSUE THREAD

**Issue by andy5995** [wikitree/wikitree-browser-extension#422]
**Describe the bug**
When Auto Bio is used, it will fill in the full names and complete dates of birth of children, siblings, etc even when the data is from profiles of living non-members.

I'm not sure if you want to consider that a bug, as the comment added by auto bio reminds the user to review and edit the changes made by auto bio.

* extension v1.8.5 on Firefox 115.0.2

**Comment by andy5995** [comment]
I see most of this was implemented. Thanks!

I'm using 1.8.8 now.

When I try it on my bio, some info still gets filled in with auto bio, such as my full name and DOB (going by this image, which says which info should be private, based on my profile privacy settings).

![image](https://github.com/wikitree/wikitree-browser-extension/assets/16764864/2ef17a35-1d12-4a25-bd8a-d117526e8c88)

**Comment by shogenapps** [comment]
Fixed.
