### ISSUE TITLE
Display issues with middle names and suffixes

### ISSUE THREAD

**Issue by eweddington** [wikitree/wikitree-browser-extension#45]
I'm seeing issues with displays of names:

- Middle names. Some profiles I see nothing for a middle name. On other profiles I see a dot (.) displayed for the middle name when there should be nothing for those profiles.
- Suffixes not displayed. I have a number of male lines that have a suffix, like "Sr" or "Jr". I don't see these displayed, when it would be helpful to see them to differentiate people at a glance.
- Suffix sometimes displayed. I have a male line with the same name that goes up to 6 in a row, with roman numerals for the suffix. For some odd reason, I do not see "VI" for one person's profile, but I see "V" on the other profile, but then nothing for "IV". I have confirmed that these are all in the Suffix field. You can see this if you start here (Cornelius Vanover VI): https://www.wikitree.com/wiki/Vanover-69 . It is also this line where I see the dot (.) for the middle name when there shouldn't be anything displayed. See below screenshot:

![image](https://user-images.githubusercontent.com/6730063/195979898-af12ac6d-aad9-4486-97e4-5d526ac0bdce.png)

**Comment by jmegenealogy** [comment]
Long names are shortened so they don't wrap.

But periods shouldn't be showing up if there isn't a middle name.

The function for shortening is `getShortName()` at https://github.com/wikitree/wikitree-dynamic-tree/blob/main/views/baseDynamicTree/WikiTreeDynamicTreeViewer.js#L601

**Comment by jmegenealogy** [comment]
I copied this to the Dynamic Tree issues.

https://github.com/wikitree/wikitree-dynamic-tree/issues/53
