### ISSUE TITLE
Improvement: Add an option to choose the font size for the Printer Friendly Bio.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#492]
There should be an option where someone can choose what font size they want to use when printing profiles.

[Rob](https://www.wikitree.com/wiki/VanNostrand-477) was the one who requested this improvement, so you may want to work with him.

**Comment by shogenapps** [comment]
I've done this. Please take a look and see what you think.
**Edit**: I've heard that this isn't working on a Mac...

**Comment by shogenapps** [comment]
I think this should be good now.
