### ISSUE TITLE
Figure out how to notify users when a new feature has been added to the extension.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#50]
> So users who install the extension for the first time should be directed to configure the options.
> 
> What is the mechanism for notifying users when a new feature has been incorporated and there are more options to be configured?

_Originally posted by @ke4tch in https://github.com/wikitree/wikitree-browser-extension/issues/13#issuecomment-1272375132_

**Comment by shogenapps** [comment]
There can be a space page documenting the new features.  With chrome.runtime.onInstalled, we can open that page on updates.

**Comment by shogenapps** [comment]
I'm going to set up three WikiTree space pages: 

1. To show the features (title: WikiTree Browser Extension (until we have a better name))
2. To show the test/preview/beta version updates
3. To show the stable version updates

The first page will be the generally available/advertised help page.  This will open on install (along with the options page).  The other two will open on update when new features are added.  We currently only have one version, so there's no problem there, but I hope people (maintainers) will be aware of this in the future and have the appropriate page open up for whatever we call the development version.  I also hope everyone will contribute to the main page to explain the features.  
The space pages will be open for editing and if anyone wants to be on the trusted list or a manager, that's fine, too. If we find that having the pages open is a bad idea, we can change that, but for now, they will be open.

**Comment by ke4tch** [comment]
So for 1. are you thinking of something akin to https://www.wikitree.com/wiki/Help:Apps so that individual extensions can then point off to the applicable help? Examples of those might be https://www.wikitree.com/wiki/Space:WikiTree_AGC or https://www.wikitree.com/wiki/Space:BioCheckHelp. Note that the latter is again one of those things that needs to be shared across the browser extension and apps, and potentially the family tree and tools in the future.

**Comment by shogenapps** [comment]
> So for 1. are you thinking of something akin to https://www.wikitree.com/wiki/Help:Apps so that individual extensions can then point off to the applicable help? Examples of those might be https://www.wikitree.com/wiki/Space:WikiTree_AGC or https://www.wikitree.com/wiki/Space:BioCheckHelp. Note that the latter is again one of those things that needs to be shared across the browser extension and apps, and potentially the family tree and tools in the future.

No. I'm thinking more something like this: https://www.wikitree.com/wiki/Space:WikiTree_BEE (explaining each feature). But I do realise that BioCheck already has a huge help page and the logical thing to do would be to link to that.

**Comment by shogenapps** [comment]
I've made a start on the space page: https://www.wikitree.com/index.php?title=Space:WikiTree_Browser_Extension .
It's open for editing, so please dive in and add images and things.  I will add an update space page and the code to open it on update soon.  

We will need think about how we're going to deal with two versions (stable and development) soon.  I guess this will mean we actually have 6 versions: Chrome, Firefox, and Safari x2.

**Comment by ke4tch** [comment]
I added some things for Bio Check. From the end user perspective, it is the exact same code as the stand alone app (well it is the same code except for how it starts). So someone who uses the standalone app to check random profiles or wt+ query results (or their watchlist, or their CC#) will be seeing the same checker code when they subsequently edit a profile found in that manner.

**Comment by shogenapps** [comment]
I've created an update space page: https://www.wikitree.com/index.php?title=Space:WikiTree_Browser_Extension_Update. We only need one (at least for now).  
And I've added something to public/background.js to open the update page on update.  I think this should be used when there's a new feature - not just when the extension has been updated with some fixes/patches.

**Comment by ke4tch** [comment]
The update page should be named release notes. The versions should be latest at the top, and should include the date. If the user sees only 3 digits then only 3 should be listed. I also suggest Known Problems at the top. What has worked good for me is a top entry with a version and date TBD, that then get updated on a release. We also need updates to Contributing.md once we agree on how to do this.

See examples here https://www.wikitree.com/wiki/Space:WikiTree_Sourcer_Release_Notes and here https://www.wikitree.com/wiki/Space:BioCheckHelp#Release_Notes. The future BioCheck remind me for the things in the extension that will be in the next released app
