### ISSUE TITLE
Fan Chart link in profile top bar opens empty page

### ISSUE THREAD

**Issue by brezelman** [wikitree/wikitree-browser-extension#538]
**Describe the bug**
The Fan Chart link in the profile "toolbar" opens https://apps.wikitree.com/apps/clarke11007/fan.php, which just shows an empty page.

**To Reproduce**
1. Go to https://www.wikitree.com/wiki/Downey-382
2. Click on the Fan Chart in the profile top bar.

**Expected behavior**
A page with a fan chart or option to show a fan chart is opened.

**Actual behavior**
An empty page opens.

**Screenshots**
![grafik](https://github.com/wikitree/wikitree-browser-extension/assets/10890091/8fa56e0c-904c-4cbb-b5b9-1cc3b5a5fc26)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 123.0.1 (64-bit)

**Comment by shogenapps** [comment]
Oh, thanks for pointing that out.  I'll remove it from WikiTree BEE.  (To see the Fan Chart, go to the new version on the Tree Apps page.)
