### ISSUE TITLE
BioCheck Sources for Add Person

### ISSUE THREAD

**Issue by ke4tch** [wikitree/wikitree-browser-extension#58]
Currently the bioCheck extension will check the profile from the Edit page. Add the ability to check the sources that are entered on the Add Person page, and provide some message (TBD) if the source is not adequate.

**Comment by ke4tch** [comment]
How to describe the list of sources? The help page for Sources FAQ when a Unsourced Research Note Box should be used uses the phrase "no source citations that clearly identify the source.". Does it make sense to adapt that as "Sources not clearly identified" as the list heading? Alternatives could be "Vague sources" or "Ambiguous sources'. Invalid sources is not user friendly.

**Comment by jmegenealogy** [comment]
"Incomplete sources" might also work?

**Comment by ke4tch** [comment]
Used "sources that are not clearly identified", since this mimics the Sources FAQ help page.

In the case of Pre-1700 used "sources that are not reliable or clearly identified"
