### ISSUE TITLE
Add options interface for AGC options

### ISSUE THREAD

**Issue by RobPavey** [wikitree/wikitree-browser-extension#59]
The AGC feature within the extension has a set of options to control its behavior. This is how the options show up in the WikiTree AGC extension:

![Screen Shot 2022-10-13 at 10 26 19 AM](https://user-images.githubusercontent.com/90426092/196269892-bcdf6e00-681a-44cf-bbed-8f4ab5a4c759.png)

I would like to add these options into the WBE options user interface. This will require some design work and probably some redesign of the current options code. So I'm opening this issue to discuss the design before starting on the coding.

I can try to design it such that each feature can register a set of options and the common code handles saving and restoring the options and building the user interface (HTML page) for the options. This is how the [wikitree-sourcer ](https://github.com/RobPavey/wikitree-sourcer) extension works and it is very modular. To add options for a new site in Sourcer the only change needed in shared code is to add one import line.

A few UI design choices have been mentioned.

1. A style like WikiTree Sourcer where there could be a tab for each category and within each tab a dropdown for each feature. (See screenshot below)
2. Like this existing design with all the categories and features in a flat scrollable page but with the ability to expand/collapse on a feature to reveal/hide its options.
3. To not use the options page at all for an individual feature but have some feature specific way of getting to its options.

Here is a screen shot of the Sourcer options page: 
![Screen Shot 2022-10-13 at 7 28 48 PM](https://user-images.githubusercontent.com/90426092/196272075-74cea992-4a13-41c0-b319-ba871db74d1c.png)

Any thoughts?

**Comment by jmegenealogy** [comment]
> I can try to design it such that each feature can register a set of options and the common code handles saving and restoring the options and building the user interface (HTML page) for the options. This is how the [wikitree-sourcer ](https://github.com/RobPavey/wikitree-sourcer)extension works and it is very modular. To add options for a new site in Sourcer the only change needed in shared code is to add one import line.

This is how I was hoping things would go, where very little has to change in the shared code to add extra options. I just wasn't sure how to implement something like that.

For the UI, I slightly prefer option 2.

**Comment by shogenapps** [comment]
I prefer option 2, too.

**Comment by RobPavey** [comment]
I have an implementation of option 2. The AGC options are pretty complicated but I have made it work. I'm still cleanng up the code but this is what it looks like.

If a feature has options the "Show Options" button will be displayed:
![Screen Shot 2022-10-20 at 10 47 22 AM](https://user-images.githubusercontent.com/90426092/197021605-a93cd0d3-4a33-467e-8765-fbc209713ea4.png)

When you show the options they are displayed within the feature:
![Screen Shot 2022-10-20 at 10 47 06 AM](https://user-images.githubusercontent.com/90426092/197021678-573a0db5-f334-44e7-9387-587dbabe99f8.png)

**Comment by jonmcrawford** [comment]
Thats nice Rob

**Comment by jmegenealogy** [comment]
Yeah, that's really nice, thanks for working on this!

**Comment by RobPavey** [comment]
This is now implemented
