### ISSUE TITLE
Remove all Club badges from displaying on profile

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#79]
Club badges are usually piling up in the badges display.

Ideally there would be a button on user's profile next to the badges to "HIDE CLUB BADGES". It would mark all club 100 and club 1000 badges from display.

If that is a problem we could have a button on 
https://www.wikitree.com/index.php?title=Special:Badges
to hide all club badges. Or maybe leave the one for previous month.

Another good addition on https://www.wikitree.com/index.php?title=Special:Badges would be to move all club babges to the end. Or maybe leave the one for previous month at the top.

**Comment by shogenapps** [comment]
I'm working on this.
