### ISSUE TITLE
Rename of Options category Other

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#87]
Instead of Other it should be named "My WikiTree" where items related to users pages would be placed. 

The option "Other / Sort Badges" is the first candidate, Maybe also Watch list related things and so on.

Aleš

**Comment by shogenapps** [comment]
I'm hoping for some more input on this.  I don't know if 'Other' is the best name for the category, but I'm not sure if 'My WikiTree' is the best either (though it could be).

**Comment by RobPavey** [comment]
I think we should update the code to separate the category id and the category text. Then we should make the category text more descriptive. I don't think "Global" will mean much to most users, in fact it may mean different things to each of the developers already! It could be changed to "Global - affects all WikiTree pages" or something like that.

I think the way we are going we are going to end up with a *lot* of features and at some point we should consolidate some features together with individual options within the feature, this could help with efficiency as well.

**Comment by RobPavey** [comment]
> I'm hoping for some more input on this. I don't know if 'Other' is the best name for the category, but I'm not sure if 'My WikiTree' is the best either (though it could be).

One other option would be "My Profile". However, I don't think there is any hurry to change it. It is a known problem that you can't come up with a good way to categorize a set of things until you have a good idea of what might be in the set. We just don't know much yet about what other features will be added.

**Comment by Lesko987** [comment]
I am almost sure that there will be a set of options related to the user's pages. That would include Badges, Tags, Watchlist, DNA, ... Basically all pages in My WikiTree menu are for user.

**Comment by RobPavey** [comment]
> I am almost sure that there will be a set of options related to the user's pages. That would include Badges, Tags, Watchlist, DNA, ... Basically all pages in My WikiTree menu are for user.

Categorization will be an ongoing challenge. If "global" means that it affects all WikiTree pages that it seems to me that Dark Mode should be under global.

But we need a policy on what the categories mean. One approach is based on what WikiTree pages they affect. If one feature only affects the Watchlist and one only affects the user's profile page then should they be in the same category? It sounds like you think they should both be under "My WikiTree".

**Comment by ke4tch** [comment]
And then again there are things like Bio Check that go on the Edit/Add person pages and also on watchlist. So where does that one feature belong?

**Comment by shogenapps** [comment]
I think WBE has developed a lot since this discussion and we still seem to need 'Other', so I'm closing this.
