### ISSUE TITLE
categoryFinderPins: Category Finder Pins Should work on all Edit pages.

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#89]
That is a great option, but it is available only on profiles. I already needed it on Category page, but since the categorisation is done on all pages, it should work everywhere.

I would also suggest different image. The one used I understand more like location related thing.  Like Pin on the map.

Aleš

**Comment by shogenapps** [comment]
OK. I can include this anywhere. 
I'm open to suggestions for the image. I realised that it kind of changed the meaning of the pin, but I also thought that people were used to seeing that and they could understand that it linked to something.

**Comment by shogenapps** [comment]
I've done both of these things.
