### ISSUE TITLE
distanceAndRelationship: missing "nephiew" in first line of relationship box

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#92]
In first line of the relationship box where the relationship should be displayed, I am getting just "Your" 

For my nephiew
Your
Your common ancestor, [Jelena (Stupica) Trtnik (1942-)](https://www.wikitree.com/wiki/Stupica-8), is his grandmother.
Your common ancestor, [Mitja Dimitrij Trtnik (1940-1994)](https://www.wikitree.com/wiki/Trtnik-4), is his grandfather.
Aleš

**Comment by shogenapps** [comment]
Thanks. I'll take a look.

**Comment by shogenapps** [comment]
I've fixed this.
