### ISSUE TITLE
collapsibleDescendantsTree: Error in debug window

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#93]
**Describe the bug**
I am getting this error in debug console after I click Descendants button on any profile.

Uncaught ReferenceError: theLIS is not defined collapsibleDescendantsTree.js:13 
    at collapsibleDescendantsTree.js:13:1
    at NodeList.forEach (<anonymous>)
    at collapsibleDescendantsTree.js:11:1
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (collapsibleDescendantsTree.js:10:1)

**Comment by shogenapps** [comment]
Thanks. I'll take a look.

**Comment by PeWu** [comment]
There's a const missing in line 13:

const theLIS = $(added_node).find("li");

I'm on a phone so I can't make the PR

**Comment by shogenapps** [comment]
> There's a const missing in line 13:
> 
> const theLIS = $(added_node).find("li");
> 
> I'm on a phone so I can't make the PR

Yes. Thank you.
